### ISSUE TITLE
Success DELETE operation raises python Exception

### ISSUE THREAD

**Issue by oodarchenko-rapidsos** [team-telnyx/telnyx-python#81]
`TelnyxResponse` object can't parse empty API response body for 204 No Content status.

https://github.com/team-telnyx/telnyx-python/blob/master/telnyx/api_requestor.py#L282

![image](https://github.com/team-telnyx/telnyx-python/assets/164196240/641ec10f-d590-4a39-9ceb-9fb03106f569)

**Comment by ADandyGuyInSpace** [comment]
Fixed in latest release (2.1.3)

**Comment by daradib** [comment]
The latest release explicitly calls `TelnyxResponse("", rcode, rheaders)`. The empty string still fails to parse as JSON.

Perhaps you meant `TelnyxResponse("{}", rcode, rheaders)`?
